---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: node:16
  commands:
  - yarn install
  - yarn build

image_pull_secrets:
- dockerconfigjson

trigger:
  ref:
  - refs/pull/**
  - refs/heads/main

...
